-- MySQL Script generated by MySQL Workbench
-- Tue Mar 28 16:29:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Passport`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Passport` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Passport` (
  `idPassport` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Patronomyc` VARCHAR(45) NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `BirthDate` DATE NOT NULL,
  `Nationality` VARCHAR(45) NOT NULL,
  `Authority` VARCHAR(45) NOT NULL,
  `IssueDate` DATE NOT NULL,
  `ExpiryDate` DATE NOT NULL,
  `ITN` INT NOT NULL,
  `Record` INT NOT NULL,
  PRIMARY KEY (`idPassport`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Passport`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Passport` (`idPassport`, `Name`, `Surname`, `Patronomyc`, `Gender`, `BirthDate`, `Nationality`, `Authority`, `IssueDate`, `ExpiryDate`, `ITN`, `Record`) VALUES (123456789, 'Mykhailo', 'Ishchenko', 'Dmytrovych', 'M', '2001.07.31', 'Ukraine', '1234', '2023.03.28', '2033.03.28', 1234567890, 1);

COMMIT;

